version: '3'
services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_LOCAL_PORT}:${NGINX_REMOTE_PORT}

  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    ports:
      - ${PHP_FPM_LOCAL_PORT}:${PHP_FPM_REMOTE_PORT}

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    image: mysql:5.7
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_REMOTE_PORT}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: redis:5
    volumes:
      - ./.docker/redis/data/:/data
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_REMOTE_PORT}
